# Usa una imagen base de Node.js
FROM node:20

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de package.json y package-lock.json
COPY client/package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos del cliente
COPY client/ .

# Construye la aplicación del cliente
RUN npm run build

# Usa una imagen base de nginx para servir la aplicación construida
FROM nginx:alpine
COPY --from=0 /app/build /usr/share/nginx/html

# Expone el puerto en el que se servirá la aplicación del cliente
EXPOSE 3000
