version: '3.8'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'sdh_inc_chat'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./chat.sql:/docker-entrypoint-initdb.d/chat.sql

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
    environment:
      NODE_ENV: production
      DB_HOST: host.docker.internal
      DB_USER: root
      #DB_PASSWORD: contraseña
      DB_DATABASE: sdh_inc_chat

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"
    volumes:
      - ./client:/app
    environment:
      NODE_ENV: production

volumes:
  db_data:
