# Usa una imagen base de Node.js
FROM node:20

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de package.json y package-lock.json
COPY server/package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos del servidor
COPY server/ .

# Expone el puerto en el que se ejecutará el servidor
EXPOSE 3000

# Comando para ejecutar la aplicación del servidor
CMD ["node", "index.js"]
